"""User Role asignation

Revision ID: 7b8477ed9196
Revises: 817967774d94
Create Date: 2024-07-06 18:30:37.509545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8477ed9196'
down_revision: Union[str, None] = '817967774d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
      with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_roles', type_='foreignkey')
        batch_op.drop_column('role_id')
    # ### end Alembic commands ###
